### ISSUE TITLE
Dummy worldguard flag boolean

### ISSUE THREAD

**Issue by 0tickpulse** [0tickpulse/lcc-utils#1]
just a set of dummy worldguard flags with a boolean value to be used with this extension

• `mmskills-blocked`
• `mmsummons-blocked`
• `mmgeneric-blocked`

This is a repost of [an issue from my previous project](https://github.com/0tickpulse/lcc-mythicmobs-utilities/issues/2).

**Comment by 0tickpulse** [comment]
@LcorpOfficial are you okay with a configurable list of flags in the config.yml, applying on each restart?

**Comment by LcorpOfficial** [comment]
That would be perfect

**Comment by 0tickpulse** [comment]
Splendid

**Comment by 0tickpulse** [comment]
Currently, the plugin generates a config file in `~/plugins/LCCUtils/worldguard_custom_flags.yml` with the contents:
```yml
flags:
  # <flag_name>: <default_value>
  myflag: true
```
You can then edit this file to have your own flags.
Is this fine?

**Comment by 0tickpulse** [comment]
Added via 2.1
